name: Trigger Workflows (Manual)

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set Release Tag Name
      id: set_tag
      run: echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Create Release with Date
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        repo=${{ github.repository }}
        tag_name=${{ env.tag_name }}
        if ! gh release view "$tag_name" --repo "$repo" >/dev/null 2>&1; then
          gh release create "$tag_name" \
            --title "Build $tag_name" \
            --notes "Release notes for Build $tag_name" \
            --repo "$repo"
        fi

  trigger_workflows:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger bookworm-xfce-standard-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-standard-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-standard-i386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-standard-i386.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-toolbox-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-toolbox-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-ultra-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-ultra-amd64.yml/dispatches \
          -d '{"ref":"master"}'
